### ISSUE TITLE
Add a redirection to https for every URLs (not just the home page)

### ISSUE THREAD

**Issue by antoinentl** [una/una.github.io#35]
Actually some contents are accessible both in `HTTP` and `HTTPS`, an example with your last article: [http://una.im/save-offline/](http://una.im/save-offline/) and [https://una.im/save-offline/](https://una.im/save-offline/). It's a problem if you want to use Service Workers!

Actually you have just one redirection to `HTTPS`: your home page.

(And thanks for your article [Implementing "Save For Offline" with Service Workers](https://una.im/save-offline/) and all your other great posts!!!)

**Comment by stepquick** [comment]
It's a setting in cloudflare. I had this issue initially, but instead of redirects, there's an option for forcing https on the entire domain by using an asterisk. I included a screenshot of how I have mine setup:
![screen shot 2017-02-21 at 11 06 06 am](https://cloud.githubusercontent.com/assets/2521852/23173027/d3b39a50-f825-11e6-9573-cbf3e0b709da.png)

**Comment by una** [comment]
Thanks @stepquick -- I had this rule set up without the * selector :) Now its added!

**Comment by antoinentl** [comment]
:+1:
